### ISSUE TITLE
Env variables starting with digits not supported on Linux

### ISSUE THREAD

**Issue by perifer** [larsemil/46Elks#2]
Just run into and issue where my environment did not work with the the env-variables suggested by this packages, e.g `46ELKS_USERNAME`. This is because they start with digits which apparently some environments doesn't support:

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and **do not begin with a digit**.

From https://stackoverflow.com/a/2821183

I ended up replacing `46` with `FORTY_SIX_`  in the config file,  e.g `FORTY_SIX_ELKS_USERNAME`.

**Comment by larsemil** [comment]
Good catch.
I have updated the readme to using letters instead of digits. Nothing in the package itself needs changing for this.
